---
- name: Manage Standalone Apache Server
  hosts: web_server
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Deploy custom HTML file
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

    - name: Ensure Apache service is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes

